export { isEmpty } from './isEmpty'
export { isNumber } from './isNumber'
export { isObject } from './isObject'
export { isString } from './isString'
export { isBoolean } from './isBoolean'
export { isUndefined } from './isUndefined'
export { isEqual } from './isEqual'
